<?php
/**
 * DatabaseAdmin Helper - "Database Engineer" Tools
 * Extends capabilities of DatabaseManager for admin tasks.
 */

require_once __DIR__ . '/DatabaseManager.php';

class DatabaseAdmin {
    private $db;
    
    public function __construct() {
        $this->db = DatabaseManager::getInstance();
    }
    
    /**
     * Get Database Connection Status
     */
    public function getConnectionStatus() {
        try {
            $this->db->getConnection()->query("SELECT 1");
            return [
                'status' => 'connected',
                'server_info' => $this->db->getConnection()->getAttribute(PDO::ATTR_SERVER_INFO),
                'driver' => $this->db->getConnection()->getAttribute(PDO::ATTR_DRIVER_NAME),
                'version' => $this->db->getConnection()->getAttribute(PDO::ATTR_SERVER_VERSION)
            ];
        } catch (Exception $e) {
            return [
                'status' => 'error',
                'message' => $e->getMessage()
            ];
        }
    }

    /**
     * List all tables with stats
     */
    public function getTables() {
        try {
            $stmt = $this->db->getConnection()->query("SHOW TABLE STATUS");
            return $stmt->fetchAll(PDO::FETCH_ASSOC);
        } catch (Exception $e) {
            return [];
        }
    }

    /**
     * Get table columns structure
     */
    public function getTableStructure($table) {
        try {
            $stmt = $this->db->getConnection()->prepare("SHOW COLUMNS FROM `$table`");
            $stmt->execute();
            return $stmt->fetchAll(PDO::FETCH_ASSOC);
        } catch (Exception $e) {
            return [];
        }
    }

    /**
     * Browse table data
     */
    public function getTableData($table, $limit = 100, $offset = 0) {
        try {
            // NOTE: Dynamic table name usage requires strict validation or careful usage as it cannot be bound.
            // In admin context, we trust input OR we should list tables to verify it exists first.
            if (!$this->tableExists($table)) throw new Exception("Table not found");
            
            $stmt = $this->db->getConnection()->prepare("SELECT * FROM `$table` LIMIT :limit OFFSET :offset");
            $stmt->bindValue(':limit', (int)$limit, PDO::PARAM_INT);
            $stmt->bindValue(':offset', (int)$offset, PDO::PARAM_INT);
            $stmt->execute();
            return $stmt->fetchAll(PDO::FETCH_ASSOC);
        } catch (Exception $e) {
            return [];
        }
    }
    
    private function tableExists($table) {
        $tables = $this->getTables();
        foreach ($tables as $t) {
            // Key might differ based on MySQL version/case (Name vs name), usually Name in result set of SHOW TABLE STATUS
            $name = $t['Name'] ?? $t['name'] ?? '';
            if ($name === $table) return true;
        }
        return false;
    }

    /**
     * Execute Raw SQL
     */
    public function executeQuery($sql) {
        try {
            // Detect if SELECT (return data) or Action (return count)
            $stmt = $this->db->getConnection()->prepare($sql);
            $stmt->execute();
            
            if (stripos(trim($sql), 'SELECT') === 0 || stripos(trim($sql), 'SHOW') === 0) {
                return ['type' => 'result', 'data' => $stmt->fetchAll(PDO::FETCH_ASSOC)];
            } else {
                return ['type' => 'affected', 'count' => $stmt->rowCount()];
            }
        } catch (Exception $e) {
            return ['type' => 'error', 'message' => $e->getMessage()];
        }
    }

    /**
     * Export Database Dump (Structure + Data)
     */
    public function exportDatabase() {
        $tables = $this->getTables();
        $output = "-- Database Dump generated by ZIMBABU Admin\n";
        $output .= "-- Date: " . date('Y-m-d H:i:s') . "\n\n";
        $output .= "SET FOREIGN_KEY_CHECKS=0;\nSET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';\n\n";

        foreach ($tables as $t) {
            $table = $t['Name'] ?? $t['name'];
            
            // Structure
            $row = $this->db->getConnection()->query("SHOW CREATE TABLE `$table`")->fetch(PDO::FETCH_NUM);
            $output .= "\n-- Table structure for `$table`\n";
            $output .= "DROP TABLE IF EXISTS `$table`;\n";
            $output .= $row[1] . ";\n\n";
            
            // Data
            $data = $this->db->getConnection()->query("SELECT * FROM `$table`")->fetchAll(PDO::FETCH_ASSOC);
            if (count($data) > 0) {
                $output .= "-- Data for `$table`\n";
                $output .= "INSERT INTO `$table` VALUES \n";
                $rows = [];
                foreach ($data as $row) {
                    $values = array_map(function($val) {
                        return $val === null ? "NULL" : "'" . addslashes($val) . "'";
                    }, array_values($row));
                    $rows[] = "(" . implode(", ", $values) . ")";
                }
                $output .= implode(",\n", $rows) . ";\n\n";
            }
        }
        
        $output .= "SET FOREIGN_KEY_CHECKS=1;\n";
        return $output;
    }

    /**
     * Update Config File
     */
    public function updateConfigFile($configData) {
        $path = __DIR__ . '/../config/database.php';
        $content = "<?php\n/**\n * Database Config - Managed by Admin Panel\n */\n\nreturn " . var_export($configData, true) . ";\n";
        return file_put_contents($path, $content);
    }

    /**
     * --- ADVANCED ENGINEER TOOLS ---
     */

    /**
     * Create New Database
     */
    public function createDatabase($name) {
        try {
            // Need to connect without selecting DB first usually, but if we are connected we can try directly
            $this->db->getConnection()->query("CREATE DATABASE IF NOT EXISTS `$name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
            return true;
        } catch (Exception $e) {
            return false;
        }
    }

    /**
     * Get Server Process List
     */
    public function getProcessList() {
        try {
            return $this->db->getConnection()->query("SHOW FULL PROCESSLIST")->fetchAll(PDO::FETCH_ASSOC);
        } catch (Exception $e) {
            return [];
        }
    }

    /**
     * Optimize All Tables
     */
    public function optimizeAllTables() {
        $tables = $this->getTables();
        $results = [];
        foreach ($tables as $t) {
            $table = $t['Name'] ?? $t['name'];
            try {
                $this->db->getConnection()->query("OPTIMIZE TABLE `$table`");
                $results[$table] = 'OK';
            } catch (Exception $e) {
                $results[$table] = 'Error';
            }
        }
        return $results;
    }

    /**
     * MIGRATE DATABASE
     * Copies all tables from Source Profile to Target Profile
     */
    public function migrateDatabase($sourceProfile, $targetProfile) {
        try {
            // 1. Connect to Source
            $srcDSN = "mysql:host={$sourceProfile['host']};dbname={$sourceProfile['database']};charset=utf8mb4";
            $srcDB = new PDO($srcDSN, $sourceProfile['username'], $sourceProfile['password'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

            // 2. Connect to Target
            $tgtDSN = "mysql:host={$targetProfile['host']};dbname={$targetProfile['database']};charset=utf8mb4";
            $tgtDB = new PDO($tgtDSN, $targetProfile['username'], $targetProfile['password'], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);

            // 3. Get Tables from Source
            $tables = $srcDB->query("SHOW TABLE STATUS")->fetchAll(PDO::FETCH_ASSOC);
            
            $log = [];

            // 4. Iterate and Copy
            foreach ($tables as $t) {
                $table = $t['Name'] ?? $t['name'];
                
                // Get Create SQL
                $createRow = $srcDB->query("SHOW CREATE TABLE `$table`")->fetch(PDO::FETCH_NUM);
                $createSQL = $createRow[1];

                // Drop & Create on Target
                $tgtDB->exec("DROP TABLE IF EXISTS `$table`");
                $tgtDB->exec($createSQL);
                $log[] = "Table `$table` structure created.";

                // Get Data
                // Use buffered query for large tables? For now, fetchAll is simple engineer tool
                $rows = $srcDB->query("SELECT * FROM `$table`")->fetchAll(PDO::FETCH_ASSOC);
                
                if (!empty($rows)) {
                    // Bulk Insert chunks
                    $chunks = array_chunk($rows, 100);
                    foreach ($chunks as $chunk) {
                        $values = [];
                        $placeholders = [];
                        foreach ($chunk as $row) {
                            $rowValues = [];
                            foreach ($row as $val) {
                                $rowValues[] = $val;
                            }
                            $values = array_merge($values, $rowValues);
                            $placeholders[] = "(" . implode(',', array_fill(0, count($row), '?')) . ")";
                        }
                        
                        $sql = "INSERT INTO `$table` VALUES " . implode(',', $placeholders);
                        $stmt = $tgtDB->prepare($sql);
                        $stmt->execute($values);
                    }
                    $log[] = "Table `$table`: " . count($rows) . " rows imported.";
                }
            }
            
            return ['status' => 'success', 'log' => $log];

        } catch (Exception $e) {
            return ['status' => 'error', 'message' => $e->getMessage()];
        }
    }
}

